### ISSUE TITLE
Swap content of a smart object layer

### ISSUE THREAD

**Issue by genesst** [Agamnentzar/ag-psd#105]
Is there a readme/docs/examples about how to place an image into a smart object layer using this package?

**Comment by Agamnentzar** [comment]
I updated readme to hopefully explain modifying documents better: https://github.com/Agamnentzar/ag-psd#modifying-documents

But the issue here is that PSD file keeps the prerendered bitmap of layer with smart object, and you need to update that bitmap if you're updating the smart object, unfortunately there's no way to tell Photoshop to just re-render it when opening the file, so you'd need to render it yourself with all the transforms applied correctly, and then also update the composite canvas yourself if you need to use it.

**Comment by jaankoppe** [comment]
Another solution to consider: https://github.com/Agamnentzar/ag-psd/issues/147
