### ISSUE TITLE
Font size is not correct.

### ISSUE THREAD

**Issue by MarkZhongsh** [Agamnentzar/ag-psd#115]
Hello.
I found this problem when I refill the text. My PSD's font size is 58px in photoshop, but the code tell me font size is 71. Is there difference  with the unit between photoshop and this?

**Comment by Agamnentzar** [comment]
Internally, in the PSD file the base font size is stored and then the font can grow or shrink depending on the text transform. But because this is confusing to reason about inside the Photoshop they multiply that size by the transform to show final size of the font to the user in the UI. So to get the same value from the file you have to multiply it by the text transform. I'm not entirely sure how exactly they do it though, because the transform can scale the font in different directions unevenly, I suspect they're using just the Y axis scale, since it's the font height that's the relevant size.

**Comment by MarkZhongsh** [comment]
OK, thanks for your help. It seems to read the adobe's document.
