### ISSUE TITLE
Adds groups width and height

### ISSUE THREAD

**Issue by adriancmiranda** [Agamnentzar/ag-psd#182]
May I  contribute by adding the `width` and `height` properties to the group layers, is it of interest to you guys?

**Comment by Agamnentzar** [comment]
width and height is not saved in PSD file so it wouldn't make sense to add it here. It would be confusing, because it would create expectation that you need to set it when saving the file. It's also ambiguous what those values should be, some people might want it to be sum of surfaces of all sub-layers, some people might need it to clip the size to clipping group layers or masks. It's better to leave this kind of calculation to the user of the library.

**Comment by adriancmiranda** [comment]
I see! Yeah, looking at it that way makes sense. I thought about adding it in `readPsd` only, but I'd need to extend the `Layer` type to be restricted to that use (to avoid altering the `Layer` interface) and add a `"mode"` parameter. Anyways, Thanks for clarifying.
