### ISSUE TITLE
how to write text Node

### ISSUE THREAD

**Issue by fastCreator** [Agamnentzar/ag-psd#7]
how to write text Node

**Comment by Agamnentzar** [comment]
Text layers are not supported yet, sorry.

**Comment by fastCreator** [comment]
Will the future support it?

**Comment by Agamnentzar** [comment]
I looked into it and it's very complicated issue with multiple embedded file formats that lack any documentation so I can't promise it will be added anytime soon.

**Comment by jochemstoel** [comment]
@Agamnentzar I know that adding support for text layers is tricky because of the reasons you provided but if you can find the time for it, this is the most wanted feature when it comes to parsing and writing PSD files because none of the PSD parsers do this.

Does it matter in difficulty whether you need to add a text layer, or the text layer is already there? The [psd.js](https://www.npmjs.com/package/psd) package has no problems parsing text layers but it doesn't let you edit the parsed object and save that as image. (I think...)

The reason why being able to edit image but also text layers is so damn useful is because it enables easy rendering of PSD product mockups. Developers then can make (complicated) PSD templates of product mockups, logo's on buildings, cd covers etc. and render anything into the placeholders, much easier and with more possibilities than using a canvas.

Anyways if it is too difficult then that's too bad but if you think that you can do it and you have the time, not just me and @fastCreator but a lot of people will benefit from this. I mean heck, personally I would pay for such a thing.

**Comment by Agamnentzar** [comment]
Reading the data from text layer is not that hard, but writing it is complete mystery, whatever I tried to write there it just doesn't load in Photoshop anymore. The data is just some arrays with numbers and I can't find any explanation of how to interpret it. I could try looking into it more but right now I'm at the point where I don't really know what to do next.

**Comment by colshacol** [comment]
I tried to dig through the code, and although it is very well broken down and pretty clean, the  reading and writing into the bytecode stuff was over my head. -_-

I do think, though, that with how powerful and useful of a tool this could be if it could actually output changes to the document, you could even take it closed source and license it. Even if it could just do the basic things at first like changing layer x/y position and changing layer text, that alone would be worth money.

**Comment by Agamnentzar** [comment]
Support for text layers added in 4964161a38ec382488cffe3e0034e3f45e766691 (v8.0.0)

It's incomplete and can have some issues, let me know if you encounter any errors when using it.
