### ISSUE TITLE
Color modes

### ISSUE THREAD

**Issue by danixeee** [Agamnentzar/ag-psd#83]
Hey, thanks for the great library!

I am wondering if you plan or know how to implement the rest of the color modes. I have tried to parse a PSD with `CMYK` color mode, but got the error `Color mode not supported: CMYK`.

Then I saw this piece of code:

```typescript
export const supportedColorModes = [ColorMode.Bitmap, ColorMode.Grayscale, ColorMode.RGB];
const colorModes = ['bitmap', 'grayscale', 'indexed', 'RGB', 'CMYK', 'multichannel', 'duotone', 'lab'];
```

Any thoughts?

**Comment by Agamnentzar** [comment]
Do you need to get CMYK values for the pixels or you want it automatically converted to regular RGB canvas ?

**Comment by Agamnentzar** [comment]
Unfortunately it turns out that simple conversion from CMYK to RGB produces really bad results and is not very useful. Photoshop converts the colors using color profile which would require parsing color profile file (like these: https://github.com/adamcooke/lizard/tree/master/colorspaces/CMYK ) and using it to convert the colors, you'd have to pick the color profile that you want in that case too, which might not be an obvious choice.

I don't know how complicated color profile files are but it seems it would be significant amount of research and work to implement these kind of conversions.

**Comment by danixeee** [comment]
Thanks for the quick response. It does not look trivial, at least for me, since I don't have enough domain knowledge to implement that.
